### ISSUE TITLE
Porting to FriendUP

### ISSUE THREAD

**Issue by titlestad** [naTmeg/ScriptedAmigaEmulator#19]
Hey! I'm porting this to FriendUP - a new cloud operating system inspired by TRIPOS / Amiga OS. Should I patch against this repository or make a new one?

Check out: https://github.com/FriendSoftwareLabs/friendup

There are changes being done to file system integration with Friend, GUI and Friend paths (instead of relative urls for web paths, it's Progdir:images/ etc like the good old Amiga, as all files are on Friend disks).

**Comment by naTmeg** [comment]
Hi there, this is good news.

I think it's better to start an own repository, because SAE should not have patches for a specific OS.
The goal is to be most compatible with no dependencies on 3rd-party-struff.
