### ISSUE TITLE
Names pipes + debug channel missing

### ISSUE THREAD

**Issue by quartexNOR** [naTmeg/ScriptedAmigaEmulator#22]
The utils.js file has a neat pipe sub-system implemented, but they seem to be decoupled from the uae side of things. Being able to open named pipes, or at least use the debug channel would be of great benefit.
Implementing a virtual filesystem is quite difficult, but if a named pipe could be used to quickly move data between the 68k world and JS world, then i could make a 68k application to bridge the gap.

Hope you have a look at it. The SAE project holds great promise.
Im de-coupling the code from the DOM so that I can run it under node.js and essentially stream the audio + video back. This allows me to use several cpu cores (clustered) in my setup.

Again, fantastic work and hope you could have a look at getting these final missing pieces into the codebase :)

**Comment by naTmeg** [comment]
See comments on issue #21.
