### ISSUE TITLE
Problem with Winter Games?

### ISSUE THREAD

**Issue by dirkwhoffmann** [naTmeg/ScriptedAmigaEmulator#28]
Hi Rupert,

while hunting some bugs in vAmiga we stumbled across a problem with WinterGames in SAE. It stops with "Software error - task held" in SAE, but loads fine in WinUAE. 

Details: 

Winter Games (1987) (U.S. Gold)
SAE 0.9.11
Kick 1.3
WinUAE 4.2.0 (2019.04.08) 64-bit

More infos about the testing results can be found here:  

https://github.com/dirkwhoffmann/vAmiga/issues/64

**Comment by naTmeg** [comment]
Hi Dirk,

as Alessandro1970 mentioned, it seems to be a problem with the copy-protection of the original disk which triggers a Line-F exception. The cracked version from "ECA" and "New Wave" does work. I don't know why it's running in WinUAE. Maybe there's some workaround...

**Comment by naTmeg** [comment]
...I guess we can close this.
