### ISSUE TITLE
Error when booting with A1000 configuration

### ISSUE THREAD

**Issue by dirkwhoffmann** [naTmeg/ScriptedAmigaEmulator#29]
Hi Rupert,

when emulating an A1000 with a Bootstrap Rom installed, memory.js throws an error in line 2235: 

    if (mem_hardreset > 1 || (a1000_bootrom !== null && hardreset && SAER.cpu.is_hardreset())

<img width="459" alt="Screenshot 2019-06-22 at 15 07 42" src="https://user-images.githubusercontent.com/12561945/59964438-e372c900-9500-11e9-9f05-4bcd89e54e4b.png">

**Comment by naTmeg** [comment]
Fixed. Thanks for the info!
